# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "openwebinars"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true  
    vb.name = "ligero"
    # Customize the amount of memory on the VM:
    vb.memory = "512"
    vb.cpus = "1"
    vb.linked_clone = true
	file_to_disk = 'tmp/disk.vdi'
    unless File.exist?(file_to_disk)
       vb.customize ['createhd', 
                     '--filename', file_to_disk, 
                     '--size', 500 * 1024]
    end
    vb.customize ['storageattach', :id, 
                   '--storagectl', 'SATA Controller', 
                   '--port', 1, 
                   '--device', 0, 
                   '--type', 'hdd', 
                   '--medium', file_to_disk]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
