Vagrant.configure("2") do |config|
    config.vm.box = "dummy"
    config.ssh.keys_only = false
    config.vm.provider :aws do |aws, override|
      aws.keypair_name = "clave-aws"
      aws.ami = "ami-3291be54"
      override.ssh.username = "admin"
    end
 end