Vagrant.configure("2") do |config|
    config.vm.define "web" do |nodo1|
      nodo1.vm.box = "debian/jessie64"
      nodo1.vm.hostname = "web"
      nodo1.vm.network "public_network", bridge: "eth0"
      nodo1.vm.network "private_network", ip: "10.0.100.101"
    end
    config.vm.define "db" do |nodo2|
      nodo2.vm.box = "debian/jessie64"
      nodo2.vm.hostname = "db"
      nodo2.vm.network "private_network", ip: "10.0.100.102"
    end
  end